### PR TITLE
bumpped cats to 0.4.1 and scalajs to 0.6.7

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by milessabin** [comment]
:+1:

**Comment by milessabin** [comment]
Oh, whoops ... needs rebase I think.

**Comment by kailuowang** [comment]
@milessabin :blush: just rebased and is going to test locally with Alleycats this time.

**Comment by kailuowang** [comment]
tested locally with Alleycats, worked fine.

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
